services:
  mongodb:
    image: mongo:5.0
    expose:
      - "27017"
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongodb:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 40s
    attach: false
  chrome:
    image: browserless/chrome
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      - DEFAULT_HEADLESS=true
      - DEFAULT_ARGS=--disable-gpu,--no-sandbox,--disable-dev-shm-usage
    attach: false
      
