---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.24.7-bookworm

inputs:
  - name: dp-component-test
    path: dp-component-test

run:
  path: dp-component-test/ci/scripts/build.sh
